[providers]

[providers.weatherbell.views.wa2mtemp]
timespanhours=36
viewtype="model"
product="ecmwf-deterministic"
region="washington"
parameter="t2m_f"
label_timezone="America/Los_Angeles"
cyclehours=[0,12]

[providers.weatherbell.views.wagusts]
timespanhours=36
viewtype="model"
product="ecmwf-deterministic"
region="washington"
parameter="gust_mph"
label_timezone="America/New_York"
cyclehours=[0,12]

[videos]

[videos.watempwind]
filename = "Washington-Temp-Wind"
imagesPerSecond = "2"

[[videos.watempwind.clips]]
view = "wa2mtemp"
title = "2M Temprature"
speed = "1"

[[videos.watempwind.clips]]
view = "wagusts"
title = "10M Wind Gust"
speed = "1"

# [youtube.videos.watempwind]
# title = "Washington ECMWF"
# description = "EURO run"
# privacy = "unlisted"
# tags = ["washington", "weather"]
# categoryid = "28"
