# [providers]

[providers.weatherbell.views.wa2mtemp]
timespanhours=48
viewtype="model"
product="ecmwf-deterministic"
region="washington"
parameter="t2m_f"
time_label_cords = { x = 420, y = 25 }
time_label_timezone="America/New_York"
cyclehours=[0,12]

[providers.weatherbell.views.wagusts]
timespanhours=48
viewtype="model"
product="ecmwf-deterministic"
region="washington"
parameter="gust_mph"
time_label_cords = { x = 420, y = 25 }
time_label_timezone="America/New_York"
cyclehours=[0,12]

[providers.weatherbell.views.seatacensqpf]
viewtype="meteogram"
product="ecmwf-ensemble"
region="KSEA"
parameter="indiv_qpf_24"
cyclehours=[0,12]

[videos]

[videos.watempwind]
filename = "Washington-Temp-Wind"

[[videos.watempwind.clips]]
view = "seatacensqpf"
title = "Seatac Ensemble 24 Hour QPF"
speed = "1"
time = "10"

[[videos.watempwind.clips]]
view = "wa2mtemp"
title = "2M Temprature"
speed = "5"
time = "0"

[[videos.watempwind.clips]]
view = "wagusts"
title = "10M Wind Gust"
speed = "5"
time = "0"

# [youtube.videos.watempwind]
# title = "Washington ECMWF"
# description = "EURO run"
# privacy = "unlisted"
# tags = ["washington", "weather"]
# categoryid = "28"
