[providers]

[providers.weatherbell.views.wa2mtemp]
timespanhours=72
viewtype="model"
product="ecmwf-deterministic"
region="washington"
parameter="t2m_f"
time_label_cords = { x = 405, y = 27 }
time_label_timezone="America/Los_Angeles"
cyclehours=[0,12]

[providers.weatherbell.views.wagusts]
timespanhours=72
viewtype="model"
product="ecmwf-deterministic"
region="washington"
parameter="gust_mph"
time_label_cords = { x = 413, y = 27 }
time_label_timezone="America/Los_Angeles"
cyclehours=[0,12]

[providers.weatherbell.views.12hrrain]
timespanhours=72
viewtype="model"
product="ecmwf-deterministic"
region="washington"
parameter="precip_12hr_inch"
time_label_cords = { x = 440, y = 27 }
time_label_timezone="America/Los_Angeles"
cyclehours=[0,12]

[providers.weatherbell.views.12hrsnow]
timespanhours=72
viewtype="model"
product="ecmwf-deterministic"
region="washington"
parameter="snow_12hr"
time_label_cords = { x = 467, y = 27 }
time_label_timezone="America/Los_Angeles"
cyclehours=[0,12]

[providers.weatherbell.views.2mrhumidity]
timespanhours=72
viewtype="model"
product="ecmwf-deterministic"
region="washington"
parameter="rh2m"
time_label_cords = { x = 407, y = 27 }
time_label_timezone="America/Los_Angeles"
cyclehours=[0,12]

[videos]

[videos.watempwind]
filename = "Washington-Winter-Standard-72-Hour"
scale = "-1:1080"

[[videos.watempwind.clips]]
view = "wa2mtemp"
name = "2 Meter Temperature"
speed = 5
time = 0

[[videos.watempwind.clips.texts]]
text = "2m Temp"
cords = { x = 715, y = 776 }
color = "red"
size = 20

[[videos.watempwind.clips]]
view = "wagusts"
name = "Wind Gusts"
speed = 5
time = 0

[[videos.watempwind.clips.texts]]
text = "Wind Gusts"
cords = { x = 715, y = 776 }
color = "red"
size = 20

[[videos.watempwind.clips]]
view = "12hrrain"
name = "12 Hour Rain"
speed = 5
time = 0

[[videos.watempwind.clips.texts]]
text = "12 Hour Rain"
cords = { x = 715, y = 776 }
color = "red"
size = 20

[[videos.watempwind.clips]]
view = "12hrsnow"
name = "12 Hour Snow"
speed = 5
time = 0

[[videos.watempwind.clips.texts]]
text = "12 Hour Snow"
cords = { x = 715, y = 776 }
color = "red"
size = 20

[[videos.watempwind.clips]]
view = "2mrhumidity"
name = "2m Relative Humidity "
speed = 5
time = 0

[[videos.watempwind.clips.texts]]
text = "2m Rel.\nHumidity"
cords = { x = 715, y = 765 }
color = "red"
size = 20

[youtube.videos.watempwind]
title = "Washington Winter 72 Hour Out"
description = "ECMWF 72 hours out"
privacy = "unlisted"
tags = ["washington", "weather"]
categoryid = "28"
snsalertarn = "arn:aws:sns:us-west-2:602525097839:arkstorm-prod-washington-20230213224956013200000002"
